INSERT INTO
  users (
    mentor_id,
    username,
    first_name,
    last_name,
    email,
    password,
    login_status,
    verified,
    profile_image,
    profession,
    work_company
  )
VALUES
  (
    'i628472fb9',
    'username',
    'Sam',
    'George',
    "sam.george@gmail.com",
    "$2a$10$IYWX38LAvlhVxC61HIVbpOB.yglIyrs4EKruALCzf4Dcp2TKZyClm",
    'offline',
    'true',
    'https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.lighthouselabs.ca%2Fuploads%2Ftestimonial%2Fcompany_logo%2F32%2Flighthouselabs.jpg&tbnid=okhsJOvWTBtooM&vet=12ahUKEwiYvsXIroCEAxUl5wIHHaSfAmMQMygAegQIARAy..i&imgrefurl=https%3A%2F%2Fwww.lighthouselabs.ca%2F&docid=5M-mXqYq2HM9yM&w=400&h=400&q=lighthouse%20labs&ved=2ahUKEwiYvsXIroCEAxUl5wIHHaSfAmMQMygAegQIARAy',
    'Web Mentor',
    'Lighthouse Labs'
  ),
  (
    'i628472fb9',
    'username',
    'Sammy',
    'Georgy',
    "sammy.georgy@gmail.com",
    "$2a$10$IYWX38LAvlhVxC61HIVbpOB.yglIyrs4EKruALCzf4Dcp2TKZyClm",
    'offline',
    'true',
    'https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.lighthouselabs.ca%2Fuploads%2Ftestimonial%2Fcompany_logo%2F32%2Flighthouselabs.jpg&tbnid=okhsJOvWTBtooM&vet=12ahUKEwiYvsXIroCEAxUl5wIHHaSfAmMQMygAegQIARAy..i&imgrefurl=https%3A%2F%2Fwww.lighthouselabs.ca%2F&docid=5M-mXqYq2HM9yM&w=400&h=400&q=lighthouse%20labs&ved=2ahUKEwiYvsXIroCEAxUl5wIHHaSfAmMQMygAegQIARAy',
    'Web Mentor',
    'Lighthouse Labs'
  );

INSERT INTO
  posts (
    username,
    first_name,
    last_name,
    profile_image,
    type,
    shared_post,
    post_id,
    project_id,
    content,
    upload,
    likes,
    shares,
    comments_count,
    flags,
    username_of_original_post,
    firstname_of_original_post,
    lastname_of_original_post,
    profile_image_of_original_post,
    time_of_original_post
  )
VALUES
  (
    'username',
    'Sam',
    'George',
    'https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.lighthouselabs.ca%2Fuploads%2Ftestimonial%2Fcompany_logo%2F32%2Flighthouselabs.jpg&tbnid=okhsJOvWTBtooM&vet=12ahUKEwiYvsXIroCEAxUl5wIHHaSfAmMQMygAegQIARAy..i&imgrefurl=https%3A%2F%2Fwww.lighthouselabs.ca%2F&docid=5M-mXqYq2HM9yM&w=400&h=400&q=lighthouse%20labs&ved=2ahUKEwiYvsXIroCEAxUl5wIHHaSfAmMQMygAegQIARAy',
    'user',
    'no',
    0,
    0,
    'my time at LHL was filled with fun',
    '',
    0,
    0,
    0,
    10,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'username',
    'Sam',
    'George',
    'https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.lighthouselabs.ca%2Fuploads%2Ftestimonial%2Fcompany_logo%2F32%2Flighthouselabs.jpg&tbnid=okhsJOvWTBtooM&vet=12ahUKEwiYvsXIroCEAxUl5wIHHaSfAmMQMygAegQIARAy..i&imgrefurl=https%3A%2F%2Fwww.lighthouselabs.ca%2F&docid=5M-mXqYq2HM9yM&w=400&h=400&q=lighthouse%20labs&ved=2ahUKEwiYvsXIroCEAxUl5wIHHaSfAmMQMygAegQIARAy',
    'user',
    'no',
    0,
    0,
    'another post - my time at LHL was filled with fun',
    '',
    0,
    0,
    0,
    10,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'username',
    'Sam',
    'George',
    'https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.lighthouselabs.ca%2Fuploads%2Ftestimonial%2Fcompany_logo%2F32%2Flighthouselabs.jpg&tbnid=okhsJOvWTBtooM&vet=12ahUKEwiYvsXIroCEAxUl5wIHHaSfAmMQMygAegQIARAy..i&imgrefurl=https%3A%2F%2Fwww.lighthouselabs.ca%2F&docid=5M-mXqYq2HM9yM&w=400&h=400&q=lighthouse%20labs&ved=2ahUKEwiYvsXIroCEAxUl5wIHHaSfAmMQMygAegQIARAy',
    'user',
    'no',
    0,
    0,
    'yet another post - my time at LHL was filled with fun',
    '',
    0,
    0,
    0,
    10,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );